on: workflow_dispatch
  # push:
  #   tags:
  #     - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build binary for ${{ matrix.binary-os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        binary-os: [darwin-amd, darwin-arm]
    steps:
      - name: Clone the repository.
        uses: actions/checkout@v3
      - name: Build application binaries for each os and architecture
        uses: ./.github/actions/build
        with:
          binary-os: ${{ matrix.binary-os }}
  release:
    name: Creates a release for this version.
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      - name: Download binaries from previous step
        uses: actions/download-artifact@v3
      - name: Create a new application release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: false
          files: |
            ${{ github.workspace }}/binary-darwin-amd
            ${{ github.workspace }}/binary-darwin-arm
          title: Release ${{ github.ref }}
          draft: true
